columns:
  - Fortnight Ended: object
  - Non-food Bank Credit: int64
  - Investments in Commercial Paper: int64
  - Investments in shares : int64
  - Investments in Bonds/Debentures: int64
  - Total Non-SLR Investments: int64
  - Adjusted Non-food Bank Credit: int64
  - Y-o-Y Growth in (7) (%): int64
  - Unnamed: int64
